# --- General ---
CONFIG_EVENTS=y
CONFIG_THREAD_NAME=y
CONFIG_REBOOT=y
CONFIG_WATCHDOG=y

# --- MCUboot OTA ---
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_IMG_MANAGER=y
CONFIG_MCUBOOT_IMG_MANAGER=y
CONFIG_FLASH_MAP=y

# --- Networking ---
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_MAX_CONN=6
CONFIG_NET_MAX_CONTEXTS=6
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_IPV4_AUTO=n
CONFIG_NET_DHCPV4=y
CONFIG_DNS_RESOLVER=y
CONFIG_NET_SOCKETS_SOCKOPT_TLS=y

# --- TLS / HTTPS para OTA ---
CONFIG_TLS_CREDENTIALS=y
CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_BUILTIN=y
CONFIG_MBEDTLS_ENABLE_HEAP=y
CONFIG_MBEDTLS_HEAP_SIZE=32768
CONFIG_NET_SOCKETS_TLS_MAX_CONTEXTS=1
# Módulos base necessários para ECDHE
CONFIG_MBEDTLS_ECDH_C=y
CONFIG_MBEDTLS_ECDSA_C=y
CONFIG_MBEDTLS_ECP_C=y
# Dependências de PKCS para key exchange
CONFIG_MBEDTLS_PKCS1_V15=y
# Key exchange e curvas
CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED=y
CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED=y
CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED=y
# Limita tamanho do buffer TLS para poupar RAM
CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=4096

# --- Wi-Fi ---
CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y
CONFIG_WIFI_INIT_PRIORITY=60

# --- Storage (NVS Flash) ---
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_FLASH_PAGE_LAYOUT=y

# --- OTA Flash write ---
CONFIG_STREAM_FLASH=y
CONFIG_IMG_BLOCK_BUF_SIZE=4096

# --- Hardware ---
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_LOG=y

# --- HEAP / STACK ---
CONFIG_LOG_BUFFER_SIZE=512
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=1024
CONFIG_NET_MGMT_EVENT_STACK_SIZE=768
CONFIG_NET_TCP_WORKQ_STACK_SIZE=512
CONFIG_MAIN_STACK_SIZE=3072
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1536
CONFIG_HEAP_MEM_POOL_SIZE=65536
CONFIG_ISR_STACK_SIZE=2048
CONFIG_NET_RX_STACK_SIZE=2048
CONFIG_NET_TX_STACK_SIZE=2048